name: Sync code to public repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private source repo
      uses: actions/checkout@v4

    - name: Push code to public target repo
      env:
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
      run: |
        echo $TARGET_REPO_TOKEN
        git config --global user.name "manhhung09it-cloud"
        git config --global user.email "manhhung09it@gmail.com"

        git clone https://manhhung09it-cloud:${TARGET_REPO_TOKEN}@github.com/manhhung09it-cloud/english.git target-repo

        cd target-repo
        rm -rf *
        cd ..

        rsync -av --exclude='.git' ./ target-repo/

        cd target-repo
        git add .
        git commit -m "Update from private source" || echo "Nothing to commit"
        git push origin main